### ISSUE TITLE
Not able to decode HS256 JWT?

### ISSUE THREAD

**Issue by LusciousPear** [funcool/buddy-sign#1]
Hello! I'm having problems decoding a JWT. It's signed HMAC/256

I've verified that the signature is correct using http://jwt.io ..

However, when I try to decode and verify the token with buddy, I'm getting a "nil" (which I assume means it did not pass verification). I've attached an example secret and token. Am I doing something wrong, or is there a bug? 

(def secret
  "KdnIJv7h5r--N2Na7XfS0EiHUKrZm_qucUbF6PmE6FOMrelLwzBOGEmI17Uqmaeu"
  )

(jws/unsign "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL29ycGhpZC10ZXN0LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1NGNhZmM0YzJlMGU5YzZiMTQ5ZDMwY2QiLCJhdWQiOiJIdTRxd3FRaU9nVHJCNlliT2NHTXBUQTdpNjFSNVp1SCIsImV4cCI6MTQyMjYyNTA5MCwiaWF0IjoxNDIyNTg5MDkwfQ.3wKNZzgghjpsPBi5gDwv-RkbzvhG22Npcfyl8SUZriI" secret)

**Comment by niwibe** [comment]
unsing method returns nil when token is invalid. In this case, the token is expired. And additionally your secret is in base64..., if you pass it as is to unsing function, it will be double encoded in base64, you should use something like this:

```clojure
(require '[buddy.core.codecs :as codecs])

(def secret (codecs/safebase64->bytes (str "KdnIJv7h5r--N2Na7XfS0EiHUKrZm_"
                                           "qucUbF6PmE6FOMrelLwzBOGEmI17Uqmaeu")))
```

**Comment by LusciousPear** [comment]
Ah, you nailed it. Thanks!

**Comment by thedavidmeister** [comment]
Hi, this is needed if you want to use auth0 as they provided secrets in base 64

**Comment by niwinz** [comment]
That is needed? This is a closed issue, if you think that there is an other bug, please open a new issue for it and explean it with some details making it easy to reproduce ;)

**Comment by thedavidmeister** [comment]
@niwinz was just adding some keywords that might make this come up in google search ;)
