### ISSUE TITLE
:hs512 throws NullPointerException.  :hs256 works fine.

### ISSUE THREAD

**Issue by tuddman** [funcool/buddy-sign#15]
When I attempted to essentially implement the JWS example auth, from:
https://github.com/funcool/buddy-auth/blob/master/examples/token-jws/src/authexample/web.clj

from lines 63:
https://github.com/funcool/buddy-auth/blob/master/examples/token-jws/src/authexample/web.clj#L63

and 80:
https://github.com/funcool/buddy-auth/blob/master/examples/token-jws/src/authexample/web.clj#L80

using `{:alg :hs512}`   throws a `NullPointerException`   whereas when I make the only change to `{:alg :hs256}`  it works fine and request headers are authenticated properly.

Stacktrace for :hs512:
```
java.lang.NullPointerException
	at clojure.string$lower_case.invoke(string.clj:215)
	at buddy.sign.jws$parse_header.invoke(jws.clj:100)
	at buddy.sign.jws$unsign.invoke(jws.clj:174)
	at buddy.auth.backends.token$jws_backend$reify__571._authenticate(token.clj:53)
	at buddy.auth.middleware$wrap_authentication$fn__1703$fn__1707.invoke(middleware.clj:36)
	at buddy.auth.middleware$wrap_authentication$fn__1703.invoke(middleware.clj:31)
...
```

any thoughts on what's causing the difference in execution when using a different strength encryption scheme?

**Comment by yusup-a** [comment]
in my case, hs256 throws error too.

```
IllegalArgumentException No implementation of method: :->byte-array of protocol: #'buddy.core.codecs/ByteArray found for class: org.bouncycastle.jcajce.provider.asymmetric.rsa.BCRSAPrivateCrtKey  clojure.core/-cache-protocol-fn (core_deftype.clj:554)
```

**Comment by niwinz** [comment]
The both errors are completely unrelated at quick view, so please @yusup-a  open a different issue for it for not mix different things and properly focus.

**Comment by niwinz** [comment]
@tuddman thanks for report it. At quick view, it seems that it is related to the key length.
Additionally, the example code on buddy-auth is a little bit outdated so I'll try to fix that in this days.

**Comment by niwinz** [comment]
A updated code of examples is uploaded and I can't reproduce your error. I have everything working as expected with both `:hs256` and `:hs512`.

**Comment by tuddman** [comment]
@niwinz thanks!  updating to `0.9.0` looks to have fixed it.  `:hs256` and `:hs512` both now work for me.
