### ISSUE TITLE
Documentation is slightly misleading

### ISSUE THREAD

**Issue by codahale** [funcool/buddy-sign#16]
In the ["Decrypting Data"](https://funcool.github.io/buddy-sign/latest/#decrypting-data) section, it says:

> You do not need specify the encryption algorithm explicitly, it is automatically detected, because the incoming token will come with content encryption algorithm stored in its header part.

But with 0.9.0:

```clojure
(def token (jwe/encrypt {} "ayellowsubmarine" {:alg :dir :enc :a128gcm}))
;; #'user/token
(jwe/decrypt token "ayellowsubmarine")
;; ExceptionInfo The `enc` param mismatch with header value.  clojure.core/ex-info (core.clj:4617)
(jwe/decrypt token "ayellowsubmarine" {:alg :dir :enc :a128gcm})
;; {}
```

Not specifying the encryption algorithm only works for the default value of `:a128cbc-hs256`.

Obviously not a big deal, but I figured I'd let you know.

**Comment by niwinz** [comment]
You are right.

The behavior have changed in some past version but the documentation is not reflected I think.

I will review it.

Thanks!

**Comment by niwinz** [comment]
Should be fixed.
