### ISSUE TITLE
I got error when I try a minimal example of signing key

### ISSUE THREAD

**Issue by rhacker** [funcool/buddy-sign#17]
I got this error while trying to sign resource with dsa and rsa keys: 

```
backend.utils.jwt=> CompilerException java.lang.IllegalArgumentException: No implementation of method: :->byte-array of protocol: #'buddy.core.codecs/ByteArray found for class: org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPrivateKey, compiling:(form-init4451766785895400468.clj:1:12)
```

**Comment by niwinz** [comment]
Can you provide a little bit more context, a little sample code that fails? I telling that because it there are unit test for rsa/dsa https://github.com/funcool/buddy-sign/blob/master/test/buddy/sign/jws_tests.clj#L132 that passes properly.

**Comment by rhacker** [comment]
Here is my minimal example: 
```
(ns backend.utils.jwt
  (:require
   [clojure.java.io :as io]
   [clj-time.core :as t]
   [buddy.sign.jws :as jws]
   [buddy.core.keys :as keys]))

(defn- private-key []
  (keys/private-key
   (io/resource "keys/ecprivkey.pem")))

(defn- public-key []
  (keys/public-key
   (io/resource "keys/ecpubkey.pem")))

(defn new-token
  [res]
  (let [exp (t/plus (t/now) (t/days 1))]
    (jws/sign res (private-key) {:exp exp})))

(defn from-token
  [token]
  (try
    (jws/unsign token (public-key))
    (catch Exception e
      (do (prn e)
          nil
          ))))

(comment
  (def token (new-token {:foo "bar"}))
  (jws/unsign token (pubkey))
  )
```

I hope there is no problem in conflicted deps, I have `:pedantic? :abort` on in my `project.clj`

**Comment by niwinz** [comment]
I have missing specify the algoriththm:

```clojure
(jws/sign res (private-key) {:alg :es256 :exp exp})))
```

**Comment by niwinz** [comment]
Using just your code and replacing the paths of the key pair and adding the `:es256` or `:es512` algorithm it just works.

**Comment by rhacker** [comment]
yeah, I think it should work too. I doubt there are deps conflictions in my code base.

**Comment by niwinz** [comment]
You have been able to solve the problem?

**Comment by rhacker** [comment]
@niwinz I haven't retried it yet, work on another task. I will retry soon and report the results.

**Comment by rhacker** [comment]
I think there is something wrong with my project, I'm not sure, I don't have time to debug the problem yet. But copying the example from you, everything works fine now. Thanks for helping :)

**Comment by niwinz** [comment]
Nice to know! Thanks!
