### ISSUE TITLE
buddy.sign.compact throws NullPointerException instead of proper ex-info

### ISSUE THREAD

**Issue by rauhs** [funcool/buddy-sign#19]
First: Thanks for this library! It's super easy and well documented! :)

Problem: 
Compare:

```
(ex-data
  (try
    (cm/unsign "blah" "secret") (catch RuntimeException e e)))

(ex-data
  (try
    (jws/unsign "blah" "secret") (catch RuntimeException e e)))
```

**Comment by niwinz** [comment]
Hi! Firstly, sorry for my late response.

I have executed that and I found that:
```
user=> (ex-data
  #_=>   (try
  #_=>     (cm/unsign "blah" "secret") (catch RuntimeException e e)))
{:type :validation, :auth :message}
user=> 

user=> (ex-data
  #_=>   (try
  #_=>     (jws/unsign "blah" "secret") (catch RuntimeException e e)))
{:type :validation, :cause :signature}
```

Seems like it does not raises NullPointerException. The messages are clearly inconsistent and I will fix that for the next version.

**Comment by rauhs** [comment]
This still raised a NPE:

`(cm/unsign "blah" "secret")` using the latest (0.10.0) version.

Ubuntu 15.10 with Java 1.80_77

**Comment by rauhs** [comment]
The problem seems to be that the `str/split` and vector destructing ends up passing `nil` to `safebase64->bytes` which throws an NPE forme.

**Comment by niwinz** [comment]
Unfortunatelly I can't reproduce that. Can you provide a failing test case that just fails in that way in travis?

On my environment, I always getting this:

```clojure
user=> (cm/unsign "blah" "secret")
ExceptionInfo Message seems corrupt or manipulated.  clojure.core/ex-info (core.clj:4617)
```
