### ISSUE TITLE
Claims validation in JWS

### ISSUE THREAD

**Issue by FreekPaans** [funcool/buddy-sign#22]
I was kind of surprised that `jws/unsign` does claims validation since that's not part of JWS (I think). It *is* part of JWT, which happens to be my use case so it isn't actually a problem for me. The docs say 

> buddy-sign does not offers special api for Json Web Token because it is a subset of Json Web Signature (JWS) and Json Web Encryption (JSE) specifications.

But I don't think that's correct, I think it's the other way around.

Related: the JWS spec allows anything to act as the payload, not just JSON data. The current implementation requires the message to be a map though.

Let me know if you'd be willing to do these changes, I'd be happy to write a patch for them.

**Comment by niwinz** [comment]
You are right, I found my self in that conclusion that days when jwt/jws/jwe rfc revisiting... but I didn't have time for do it. The idea is create a new namespace `jwt` and "move" all claims validation into it wit corresponding `sign/unsing` and `encrypt/decrypt` functions. Leaving jws and jwe just for raw payload signing encription.

I don't see any way to do it without breaking changes but I think it should be done in most backward compatible way. Feel free to write the first approach/version and I'll review it later.

Thanks!

**Comment by niwinz** [comment]
Hmm, I think having backward compatibility will make the code very complicated, I think a better approach is break compatibility but offer a very quick migration path (e.g: change `jws/` ns with `jwt/` ns and you are done) and document it properly.

**Comment by FreekPaans** [comment]
Yes, moving the claims validation logic from `jws` to a `jwt` namespace was my idea as well. 

Maybe we can add a param to `jws/sign` to indicate that the client is aware that claims validation has been removed, and throw if it isn't supplied. That way, clients assuming claims are checked with JWS will fail instead of always succeeding (which is bad). This parameter can be removed after some transition time.

**Comment by niwinz** [comment]
Should be considered fixed.
