### ISSUE TITLE
buddy-sign needs a hard dependency on nippy 2.11.1

### ISSUE THREAD

**Issue by voxdolo** [funcool/buddy-sign#25]
Due to [this issue](https://github.com/ptaoussanis/nippy/issues/73) in nippy 2.11.0-alpha5, `buddy-sign` should declare a hard dependency on Nippy 2.11.1, instead of [listing it as "provided"](https://github.com/funcool/buddy-sign/blob/master/project.clj#L7), which will use whatever version of Nippy happens to be available.

**Our specific scenario:**

We include carmine (2.12.2) in our project, which resolves to a dependency on Nippy 2.10.0. The result is that when trying to deserialize a JWT token with our claims, we get this error:

`Bad reply data: Thaw failed: Decryption/decompression failure, or data unfrozen/damaged.`

**Comment by niwinz** [comment]
Hi @voxdolo 
Thanks for reporting that.

In this case I think that you should declare a hard dependency in your project to a specific version of nippy instead to forcing it on buddy-sign for all users. Other users that does not uses carmine or has other version requirements may will be forced to use the buddy-sign hardcoded dependency or deal with overwritting.

Not having a hard dependency I think is more flexible an allow users to use concrete versions of it. And this seems exactly your case.

**Comment by voxdolo** [comment]
Hi @niwinz,

While it's irrefutably true that not everyone uses Carmine, Nippy is a very common dependency for libraries. Given the changes in 2.10.0-beta5, the soft dependency means that anyone upgrading to the latest `buddy-sign` that happens to have anything earlier than Nippy 2.11.1 on their classpath will find JWT unable to `unsign` claims serialized by previous versions of `buddy-sign`.

In my opinion, `:scope "provided"` makes sense for commonly available and possibly conflicting libraries, except where you literally cannot use a lesser version than x.

Thanks!

**Comment by niwinz** [comment]
Hmm, I don't agree.

Let see, that in 0.10.0 I have updated the builtin nippy from 2.9.x to 2.11.x (https://github.com/funcool/buddy-sign/blob/master/CHANGES.adoc#version-0100), so the users that are using the previous version will found with the same issue that you are telling and they will be forced to place the proper exclusion and setup own nippy version on their projects. _buddy-sign_ is not bound to specific nippy version, is only the user code that is bound to specific version of nippy (so, forcing it at _buddy-sign_ it not make sense).

The not hard-coded dependency allows more easily to users just use the version of nippy that they need on their projects removing possible frictions in dependencies setup. Your case is just the case that I want to facilitate, if your code is bound to a nippy 2.11.x, just put it on your dependencies and when (in a possible future) buddy-sign will update to other nippy version with breaking changes, this will not affect you.

PS: nippy is used in "simple message signing" that is not JWT, JWT is not affected by this cange in any manner.
