### ISSUE TITLE
The JWT 'aud' claim can be a collection.

### ISSUE THREAD

**Issue by ddeaguiar** [funcool/buddy-sign#27]
As per [section 4.1.3 of the RFC](https://tools.ietf.org/html/rfc7519#section-4.1.3),

> In the general case, the "aud" value is an array of case-
   sensitive strings, each containing a StringOrURI value.  In the
   special case when the JWT has one audience, the "aud" value MAY be a
   single case-sensitive string containing a StringOrURI value.

**Comment by niwinz** [comment]
Fixed
