### ISSUE TITLE
Any interest or help in parsing keys encoded in JWK?

### ISSUE THREAD

**Issue by dball** [funcool/buddy-sign#29]
Google's OpenID Connect system provides signed JWS tokens with their authenticity asserted by keys available in JWK format:

```
{"kty" "RSA", "alg" "RS256", "use" "sig", "kid" "21ea36ce50d7665fc1d6b01dc726f5820c02c8df", "n" "n5NuAPSEeZcmbyIdChc29OHHieMEAIJRmNbtc6IOoutbva_JX-OOuW9EzAafCblQg6Eo5x3FVCMRCNCyxRJ4d9vktGqZvpiNFlEboidqLICxP-2luMmRRA6TYSFl2dFDYin4auoN0KjsV61-WpeDp0kuPEyvxW-C1arzNJYit8RaXc7lciKiCmp4yP_e4mwqd_48ChqzgVMD0f2caWQjxwfBIp3WWYJlsKNJ-gScQp1HEds9D_N6ELQJCDImF8f2fD1cMguu0W53tTahqubyILa_MZbmOiJLMbZLauFpZOAuyG_PfFOmGlQumL_v8NO_13H4hLMOfour_sAOHfH4Nw", "e" "AQAB"}
```

which is apparently part of the OpenID Connect standard. I don't know, I've been wading in acronym soup all day now.

I'm interested in validating these using buddy, but it's not clear how to convert the `n` and `e` values into a public key of the form buddy expects. Is this possible in buddy as is?

Is there any interest in seeing buddy extended to support OpenID Connect more systemically?

**Comment by niwinz** [comment]
Hi @dball 

I have no special interest on direct support for OpenID Connect, but I gladly accept any contribution that will help the user easy to setup such things. 

Would be awesome to have support for jwk in buddy (I haven't done it because I haven't needed it). A numba-jose (java impl) already have impl for it so impl details can be learned from that library.

**Comment by niwinz** [comment]
Closing for this moment because seems no movement here.

**Comment by shen-tian** [comment]
Reviving this thread...

[here](https://gist.github.com/caryfitzhugh/55807df5f85cd54826d1476c77d752c5) is a Gist of this being done using both nimbus-jose and BouncyCastle. 

It's dragging a lot of extra dependencies just to get a small amount of work done though.

Will see if I can do anything sensible here.
