### ISSUE TITLE
Missing Implementation of -to-bytes on PersistentArrayMap

### ISSUE THREAD

**Issue by alexanderkiel** [funcool/buddy-sign#34]
The documentation has the following example:

```clojure
(require '[buddy.sign.jws :as jws])

(jws/sign {:userid 1} "secret")
;; "eyJ0eXAiOiJKV1MiLCJhbGciOiJIU..."
```

If I run this, I get the following error:

```
CompilerException java.lang.IllegalArgumentException: No implementation of method: :-to-bytes of protocol: #'buddy.core.codecs/IByteArray found for class: clojure.lang.PersistentArrayMap
```

The implementation could look something like this (encoded as JSON for JWT):

```clojure
(extend-protocol buddy.core.codecs/IByteArray
    IPersistentMap
    (-to-bytes [m]
      (buddy.core.codecs/-to-bytes (cheshire.core/generate-string m))))
```

I'm not sure about the JSON part because I currently don't understand weather JWS has always a JSON payload. I suspect no.

**Comment by alexanderkiel** [comment]
I found in the changeling that I have to replace the namespace `buddy.sign.jws` with `buddy.sign.jwt`. Than everything works as expected.

I think you should make this clear in the doc.

**Comment by niwinz** [comment]
I just updated the doc (related #33).
