### ISSUE TITLE
apply-jdk8-extensions macro is evaluated at compile-time, so JARs compiled with Java 8 JDK don't work on Java 7

### ISSUE THREAD

**Issue by camsaul** [funcool/buddy-sign#41]
It looks like the [`apply-jdk8-extensions` macro](
https://github.com/funcool/buddy-sign/blob/master/src/buddy/sign/util.clj#L52) is getting `eval`ed at compile-time, e.g. if you build a JAR the check is done whenm the JAR is built. This means if you build the JAR with a Java 8 JDK, the JAR won't work with Java 7. 

e.g. if you build a JAR with Java 8 the macro is expanded at compile-time and `(apply-jdk8-extensions)` becomes

```clojure
(extend-protocol ITimestamp
   java.time.Instant
  (to-timestamp [obj__59919__auto__] 
    (.getEpochSecond obj__59919__auto__)))
```

This doesn't work on Java 7 :/

**Comment by camsaul** [comment]
I'll submit a PR to fix this, I think something like

```clojure
(when-let [klass (try (Class/forName "java.time.Instant")
                      (catch ClassNotFoundException _))]
  (extend ITimestamp
    klass
    {:to-timestamp (fn [this]
                     (.getEpochSecond this))}))
```

should work

I still need to figure out how to deal with the reflection warning since we can't tag `this` with `java.time.Instant`

**Comment by camsaul** [comment]
I've submitted a PR to address this issue and make sure the checks actually happen at runtime here: #42

**Comment by niwinz** [comment]
1.5.0 released ;)
