### ISSUE TITLE
Cannot get "kid" of JWT token from decode-header

### ISSUE THREAD

**Issue by denisw** [funcool/buddy-sign#44]
When verifying a JWT token from an external source (e.g., an ID token in an OpenID Connect flow), it is necessary to read the `kid` of the signing key from the token header in order to fetch the correct signing key (e.g. from a JWK Key Set URL), before unsigning.

`buddy.sign.jws/decode-header` seems to be perfect for this, but unfortunately it selectively extracts the `typ` and `alg` attributes instead of the full header (which includes `kid`). It would be nice if either all header attributes would be returned, or if at least `kid` is included to support the OpenID Connect use case.

**Comment by niwinz** [comment]
PR is welcome to improve that!

**Comment by theikkila** [comment]
#52 implements new `buddy.sign.jws/decode-header` that can be used to extract other attributes as well
