### ISSUE TITLE
EdDSA JWS support

### ISSUE THREAD

**Issue by shilder** [funcool/buddy-sign#60]
Hello, i've added EdDSA signature algorithm for issuing JWS tokens

https://github.com/shilder/buddy-sign-eddsa

There's one issue with encoding of JWS header field - IANA lists algorithm for EdDSA as 
`EdDSA` string, but `buddy.sign.jws/encode-header` converts it to `EDSSA`, so i've monkey-patched this function to produce correct output

I can merge it with `buddy-sign`, `buddy-core` libraries, or leave at as separate library,

**Comment by niwinz** [comment]
Nice job! That will be welcome into the buddy-core and buddy-sign, please consider making a PR for that, i'm gladly will merge that.
