### ISSUE TITLE
JWS ECDSA Signatures are generated in incorrect format

### ISSUE THREAD

**Issue by shilder** [funcool/buddy-sign#62]
Hello, i'm writing tests for JWK keys support and it seems that `buddy-sign` JWS generator uses `dsa/sign` output directly, which is DER-encoded format. but according to https://tools.ietf.org/html/rfc7515#appendix-A.3 JWS signature should be concatenation of `R || S`

Nimbus-JOSE-JWT library has pair of functions `ECDSA/transcodeSignatureToConcat` and `ECDSAPart/transcodeSignatureToDER` for conversions between these two

[Nimbus ECDSA.java](https://bitbucket.org/connect2id/nimbus-jose-jwt/src/0c9bd531358cd04fdd075550ee89e90a1af4e7ab/src/main/java/com/nimbusds/jose/crypto/ECDSA.java?at=master&fileviewer=file-view-default#ECDSA.java-175)

This can be solved either by copy/pasting (Nimbus is Apache 2.0 licensed, so it's possible with copyright noitices) these functions, by inclusion of nimbus in dependencies or by rewriting code in clojure (which will not be very nice due to low-level byte juggling)

Also this change will be breaking for anyone, who issued long-lived ECDSA JWS tokens using `buddy-sign`

**Comment by niwinz** [comment]
I think that the best and more immediate approach is just creating a java class and copy that functions with appropriate copyright notice, (seems like they dont have any external dependencies, just java code...) and use them.
It is ok for the breaking change, if the previous impl is not compliant we should fix it.

Many thanks for you work

**Comment by shilder** [comment]
See #63
