### ISSUE TITLE
Cats dependency issue

### ISSUE THREAD

**Issue by drpjm** [funcool/buddy-sign#8]
I was working through this tutorial http://rundis.github.io/blog/2015/buddy_auth_part1.html and found that my require statement fails for buddy.sign.jws due to a failed dependency with cats:
```
CompilerException java.io.FileNotFoundException: Could not locate cats/monad/exception__init.class or cats/monad/exception.clj on classpath: , compiling:(buddy/sign/jws.clj:1:1)
```
Looking at my leiningen dependencies, I see cats 0.6.1. I am using Eclipse with CCW. Is there some other lein project parameter I need to get cljc files compiled correctly?

**Comment by niwinz** [comment]
That clojure version you are using? Clojure 1.7 is required version since cats 0.5.x because it starts using reader conditionals at this version.

**Comment by drpjm** [comment]
Ah yes, my Clojure dependency was 1.6. Switched to 1.7 and it works! Thanks!
