### ISSUE TITLE
JWS unsigned alg should be read out of the JOSE header if available 

### ISSUE THREAD

**Issue by alexparlett** [funcool/buddy-sign#83]
unsign requires you to know the alg before unsigning a JWS, however if you publish keys with different algorithms or you are not in control of the signing of a JWS you might not know the algorithm.

It should use the alg field from the JOSE header and only default to :hs256 if it is not present in opts or the header.

https://tools.ietf.org/html/rfc7515#section-4.1.1

**Comment by alexparlett** [comment]
This is solved by https://github.com/funcool/buddy-sign/pull/78/files can we get it looked at asap?

**Comment by shilder** [comment]
I like to control algorithms that are allowed for verification to avoid all kind of complications described in this article: https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by alexparlett** [comment]
Our use case doesnt have that choice, we need to unsign a JWS that is signed by a third party who provide a JWKS per customer and whose algorithm selection is out of our control.
