### ISSUE TITLE
buddy.sign.jwt/unsign fails when hs256 is not used and alg is unspecified

### ISSUE THREAD

**Issue by handerpeder** [funcool/buddy-sign#88]
Might be I'm missing something but I would expect this to work:

```clojure
(require '[buddy.sign.jwt :as jwt])

(->
 (jwt/sign {:foo 1} "test" {:alg :hs512})
 (jwt/unsign "test"))
```

but it fails with 
```
   Message seems corrupt or manipulated.
   {:type :validation, :cause :signature}
```

Looking at `buddy.sign.jws/unsign` it sets the algorithm to hs256 unless specified. So this works:

```clojure
(->
 (jwt/sign {:foo 1} "test" {:alg :hs512})
 (jwt/unsign "test" {:alg :hs512)) ; => {:foo 1}
 ```
 
 Shouldn't jws/unsign read the signing algorithm from the header? Something like:
 
 ```clojure
 (defn unsign
  "Given a signed message, verify it and return
  the decoded payload."
  ([input pkey] (unsign input pkey nil))
  ([input pkey {:keys [alg] :or {alg :hs256}}]
   (let [[header payload signature] (split-jws-message input)
         header-data (parse-header header)]
     (when-not
       (try
         (verify-signature {:key       (util/resolve-key pkey header-data)
                            :signature signature
                       ;;     :alg       alg           <- Change this
                            :alg     (:alg header-data) ;; <- To this
                            :header    header
                            :payload   payload})
         (catch java.security.SignatureException se
           (throw (ex-info "Message seems corrupt or manipulated."
                           {:type :validation :cause :signature}
                           se))))
       (throw (ex-info "Message seems corrupt or manipulated."
                       {:type :validation :cause :signature})))
     (decode-payload payload))))
```

**Comment by handerpeder** [comment]
My workaround for this is to call `jws/decode-header` and pass the alg to unsign:

```clojure
(require '[buddy.sign.jwt :as jwt])
(require '[buddy.sign.jws :as jws])

(def header (jws/decode-header token))

(->
 (jwt/sign {:foo 1} "test" {:alg :hs512})
 (jwt/unsign "test" (:alg header)))
```

**Comment by RokLenarcic** [comment]
Ran into a similar thing using `jwe/encrypt`->`jwe/decrypt`... the options used are in the header but never read by decrypt so it fails unless you specify the exact options that were used to encrypt. 

There's a couple of different ways this could work:
- always use values from header
- use `(merge defaults header option-map)`
- if option map is provided skip header so `(merge defaults (if option-map? option-map header))`

**Comment by niwinz** [comment]
> Ran into a similar thing using jwe/encrypt->jwe/decrypt... the options used are in the header but never read by decrypt so it fails unless you specify the exact options that were used to encrypt.

yes, this is expected, for security reasons, the algorithm should be specified explicitly
https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by niwinz** [comment]
Looking up the algorithm dynamically from the header has security implications. It is strongly recommended use a fixed algorithm and specify it explicitly.
