### ISSUE TITLE
nbf rule correct?

### ISSUE THREAD

**Issue by jonpither** [funcool/buddy-sign#9]
is this code right?

`(when (and (:nbf claims) (> now (:nbf claims)))
      (throw (ex-info (format "Token is not yet valid (%s)" (:nbf claims))
                      {:type :validation :cause :nbf})))`

This means that if now is greater than nbf, it'll throw an exception.

But nbf means "not before". So if my NBF is 11am, then I'm saying this token is invalid before 11am. 

But the code does the reverse check... so is NBF broken?

The code lives in `buddy.sign.jws`

**Comment by niwinz** [comment]
Your are completely right! I will fix it today as soon as I can.

**Comment by niwinz** [comment]
Should be fixed on buddy-sign 0.7.1 or buddy 0.7.1

Thanks for report this!
