### ISSUE TITLE
Call resolve-key in sign function on pkey

### ISSUE THREAD

**Issue by janetacarr** [funcool/buddy-sign#93]
Hey Buddy! 

I'm not sure if this entirely qualifies as an issue, so close it if not, but I just discovered that you can sign tokens with `nil` as the pkey/secret, but not unsign the same token with nil as there's no implementation of IKeyProvider (used by unsign ala `resolve-key` [here](https://github.com/funcool/buddy-sign/blob/master/src/buddy/sign/jws.clj#L141) )

So, should there be a call to resolve-key in the `sign` function? [found here](https://github.com/funcool/buddy-sign/blob/master/src/buddy/sign/jws.clj#L126)

Anyways, let me know if this was intended or not. If not, I'll open a PR.

**Comment by niwinz** [comment]
Fixed.
Thanks
